runtime: custom
env: flex
service: faceguard-backend
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/gcloud.json"
  MONGO_URI: "mongodb+srv://faceguard:itkgixXXqmTo8YyL@cluster0.quwb0.mongodb.net/deploy?retryWrites=true&w=majority"
manual_scaling:
  instances: 1
resources:
  cpu: 4
  memory_gb: 20
  disk_size_gb: 60
liveness_check:
  path: "/api/v1/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 10
  success_threshold: 5
readiness_check:
  path: "/api/v1/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 10
  success_threshold: 5
  app_start_timeout_sec: 240